routes/admin.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::namespace('Admin')->group(function () {
    Route::get('/login', 'Auth\LoginController@login')->name('admin.login');
    Route::post('/check-login', 'Auth\LoginController@checkLogin')->name('admin.checkLogin');
    Route::get('/logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('/forgot-password', 'Auth\LoginController@forgot')->name('admin.forgot_pass');
    Route::post('/recover-pass', 'Auth\LoginController@recoverPass')->name('admin.recover_pass');
    Route::get('/activate', 'Auth\LoginController@updatePass')->name('admin.update_pass');
    Route::post('/reset-new-pass', 'Auth\LoginController@resetPass')->name('admin.reset_pass');
    Route::get('/contact', 'Auth\LoginController@contact')->name('admin.contact');

    Route::group(['middleware' => ['checkLogin:admin', 'checkAdmin'],  'as' => 'admin.'], function () {
        Route::get('/', 'AdminController@index')->name('index');
        Route::get('/create', 'AdminController@create')->name('create');
        Route::post('/store', 'AdminController@store')->name('store');
        Route::get('edit/{id}', 'AdminController@edit')->name('edit');
        Route::put('update/{id}', 'AdminController@update')->name('update');
        Route::delete('destroy/{id}', 'AdminController@destroy')->name('destroy');
        Route::group(['prefix' => 'client'], function () {
            Route::get('/', 'ClientController@index')->name('client.index');
            Route::get('create', 'ClientController@create')->name('client.create');
            Route::post('store', 'ClientController@store')->name('client.store');
            Route::get('edit/{id}', 'ClientController@edit')->name('client.edit');
            Route::put('update/{id}', 'ClientController@update')->name('client.update');
            Route::delete('destroy/{id}', 'ClientController@destroy')->name('client.destroy');

            Route::get('{client_id}/employee', 'EmployeeController@index')->name('employee.index');
            Route::get('{client_id}/employee/create', 'EmployeeController@create')->name('employee.create');
            Route::post('{client_id}/employee/store', 'EmployeeController@store')->name('employee.store');
            Route::get('{client_id}/employee/edit/{id}', 'EmployeeController@edit')->name('employee.edit');
            Route::put('{client_id}/employee/update/{id}', 'EmployeeController@update')->name('employee.update');
            Route::delete('{client_id}/employee/destroy/{id}', 'EmployeeController@destroy')->name('employee.destroy');
            Route::any('{slug}', function()
            {
                return view('errors.404');
            });
        });
        Route::any('{slug}', function()
        {
            return view('errors.404');
        });
    });
});

Route::fallback(function() {
    if (Auth::check() && Auth::user()->type == User::TYPE_ACCOUNT_AA){
        return redirect()->route('admin.index');
    }else {
        return redirect()->route('admin.login');
    }
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//Route::get('/', function () {
//    return view('template/home');
//})->name('home')->middleware('auth:client');
//
//Route::get('/', function () {
//    return view('template/home');
//});
//Route::get('/admin', function () {
//    return view('template/users/index');
//});

// Route::get('/admin/create-user', 'TemplateController@createUser');
//Route::get('/admin/manage', 'TemplateController@manage');
//Route::get('/admin/create-client', 'TemplateController@createClient');
// Route::get('/admin/create-ce', 'TemplateController@createCE');

//Route::get('/login', 'TemplateController@login');
//Route::get('/forgot-password', 'TemplateController@forgot');
//Route::get('/contact', 'TemplateController@contact');
//Route::get('/reset-password', 'TemplateController@resetPwd');

// Route::get('/create-question', 'TemplateController@createQuestion');
// Route::get('/question-list', 'TemplateController@questionList');
// Route::get('/preview', 'TemplateController@preview');
// Route::get('/address-list', 'TemplateController@addressList');
// Route::get('/create-address', 'TemplateController@createAddress');
// Route::get('/confirm-address', 'TemplateController@confirmAddress');
// Route::get('/create-csv', 'TemplateController@createCsv');
// Route::get('/csv-detail', 'TemplateController@csvDetail');
// Route::get('/statistic-list', 'TemplateController@statisticList');
// Route::get('/statistic-detail', 'TemplateController@statisticDetail');

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Client extends Model
{
    use SoftDeletes;

    protected $table = 'clients';
    protected $primaryKey = 'id';
    protected $fillable = [
        'code',
        'name',
        'name_furi',
        'first_name',
        'last_name',
        'first_name_furi',
        'last_name_furi',
        'email',
        'tel',
        'fax',
        'post_code',
        'address',
        'hp',
        'note',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by',
        'updated_by',
    ];

    /**
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->last_name . ' ' . $this->first_name;
    }

    public function getPhoneAttribute()
    {
        return formatPhone($this->tel);
    }

    public function getCheckAttribute()
    {
        $check = false;
        $employee = User::where(['client_id' => $this->id, 'type' => User::TYPE_ACCOUNT_CE])->first();
        if ($employee != '') $check = true;

        return $check;
    }

    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function customers()
    {
        return $this->hasMany(Customer::class);
    }

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['fullname', 'phone', 'check'];
}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ClientRequest;
use App\Repositories\Eloquent\ClientRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Config;

class ClientController extends Controller
{
    private $clientRepository;
    private $dirView = 'admin.clients.';

    /**
     * ClientController constructor.
     *
     * @param ClientRepository $clientRepository
     */
    public function __construct(ClientRepository $clientRepository)
    {
        $this->clientRepository = $clientRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keySearch = $request->has('keyword') && $request->keyword != '' ? $request->keyword : '';
        $page = @$request->page ?? 1;
        $sort = @$request->sortOrder ?? 'asc';
        $sortColumn = @$request->column ?? 'code';
        if (@$request->sortOrder == 'all') {
            $sort = 'asc';
            $sortColumn = 'code';
        }
        if (@$request->column == 'fullname') $sortColumn = 'first_name';
        $data['lists'] = $this->clientRepository->listClient([
            'select' => ['id', 'code', 'name', 'name_furi', 'first_name', 'last_name', 'email', 'tel', 'address', 'hp', 'note', 'updated_at'],
            'page' => $page,
            'order_sort' => $sort,
            'order_by' => $sortColumn,
            'search' => $keySearch,
            'per_page' => Config::get('const.ITEMS_PER_PAGE'),
        ]);
        $data['count'] = $data['lists']->total();

        if ($request->ajax()) {
            return response()->json([
                'paginate' => view('paginate')->with('lists', $data['lists'])->render(),
                'data' => view($this->dirView . 'box_table')->with('lists', $data['lists'])->render()
            ]);
        }

        return view($this->dirView . 'index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $data['code'] = $this->clientRepository->getLatestCode();

        return view($this->dirView . 'create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ClientRequest $request)
    {
        try {
            $data = $request->all();
            $this->clientRepository->store($data);

            return redirect()->route('admin.client.index')->with('success', 'クライアントの登録が完了しました。');
        } catch (\Exception $exception) {
            return redirect()->route('admin.client.index')->with('error', $exception->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $data = $this->clientRepository->edit($id);

        return view($this->dirView . 'edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ClientRequest $request, $id)
    {
        try {
            $data = $request->all();
            $this->clientRepository->updateClient($id, $data);

            return redirect()->route('admin.client.index')->with('success', 'クライアントの編集が完了しました。');
        } catch (\Exception $exception) {
            return redirect()->route('admin.client.index')->with('error', $exception->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        try {
            $client = $this->clientRepository->findOrFail($id);
            $client->update(['updated_by' => auth()->user()->id]);
            $client->delete();

            return redirect()->route('admin.client.index')->with('success', 'クライアントの削除が完了しました。');
        } catch (\Exception $exception) {
            return redirect()->route('admin.client.index')->with('error', $exception->getMessage());
        }
    }
}

app/Http/Controllers/Client/CheckEmailController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\FailedEmail;
use Carbon\Carbon;
use Illuminate\Http\Request;

class CheckEmailController extends Controller
{
    public function index()
    {
        $inputJSON = file_get_contents('php://input');
        error_log($inputJSON);
        $data = json_decode($inputJSON, TRUE);
        if ($data) {
            $dataSave = [];
            $eventError = ['bounce', 'spamreport', 'dropped', 'deferred'];
            foreach ($data as $key => $row) {
                if (in_array($row['event'], $eventError)) {
                    $checkExistsEmail = FailedEmail::query()->where(['email' => $row['email']])->first();
                    if (!empty($checkExistsEmail)) {
                        $checkExistsEmail->update(['time' => date('Y-m-d H:i:s', $row['timestamp'])]);
                    } else {
                        $dataSave[] = [
                            'email' => $row['email'],
                            'type' => $row['event'],
                            'time' => date('Y-m-d H:i:s', $row['timestamp']),
                            'created_at' => Carbon::now(),
                        ];
                    }
                }
            }
            if (!empty($dataSave)) FailedEmail::insert($dataSave);
        }
        return response()->json(['status' => true]);
    }
}

app/Http/Controllers/Client/CustomerSurveyController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Http\Requests\CustomerSurveyRequest;
use App\Models\Survey;
use App\Repositories\CustomerSurveyRepositoryInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Str;

class CustomerSurveyController extends Controller
{
    private $customerSurveyRepository;
    private $dirView = 'client.customer_survey.';

    public function __construct(CustomerSurveyRepositoryInterface $customerSurveyRepository)
    {
        $this->customerSurveyRepository = $customerSurveyRepository;
    }

    /**
     * Render modal send mail
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function modalSend(Request $request)
    {
        $arrCustomer = $request->has('arrCustomer') && !empty($request->arrCustomer) ? $request->arrCustomer : [];
        $data = $this->customerSurveyRepository->renderData($arrCustomer);

        return view($this->dirView . 'form_send', $data);
    }

    public function getSurvey(Request $request)
    {
        $data = [];
        $id = $request->has('id') && $request->id != '' ? $request->id : '';
        $url = url('/answer-survey?id=' . base64_encode($id));
        if ($id) $data['url'] = $url;

        return view($this->dirView . 'message_mail', $data);
    }

    /**
     * Preview mail send
     *
     * @param CustomerSurveyRequest $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function modalConfirm(CustomerSurveyRequest $request)
    {
        $data = $request->all();
        if ($data['question_package_id'] != '') {
            $survey = Survey::findOrFail($data['question_package_id']);
            if ($survey != '') $data['survey_name'] = $survey->title;
        }
        $data['message'] = $data['old_message'];

        return view($this->dirView . 'form_confirm', $data);
    }

    /**
     * Submit send email to customer
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function submitSendMail(Request $request)
    {
        $data = $request->all();
        $submitMail = $this->customerSurveyRepository->submitMail($data);
        if ($submitMail) {
            return view($this->dirView . 'success');
        }

        return view($this->dirView . 'error');
    }

    public function resendEmail(Request $request)
    {
        $id = $request->survey_id;
        try {
            $resend = $this->customerSurveyRepository->resendEmail($id);
            if ($resend['status']) return view($this->dirView . 'success');

            return view($this->dirView . 'error')->with('failEmail', @$resend['fail_email']);
        } catch (\Exception $e) {
            return redirect()->route('client.customer.index')->with('error', $e->getMessage());
        }
    }
}

resources/views/admin/clients/box_table.blade.php
@if($lists->isNotEmpty())
    @foreach($lists as $row)
        <tr>
            <td class="main_table_action">
                <a href="javascript:void(0);" data-id="{{ $row->id }}" data-url="{{ route('admin.client.destroy', $row->id) }}"
                   class="delete-client {{ $row->check ? 'disable' : '' }}"
                   data-toggle="modal" data-target="#deleteClient">
                    <i class="fas fa-trash-alt main_icon m-0"></i>
                </a>
            </td>
            <td class="main_table_action">
                <a href="{{ route('admin.client.edit', $row->id) }}"><i
                        class="fas fa-pen main_icon m-0"></i></a>
            </td>
            <td><a href="{{ route('admin.employee.index', $row->id) }}" class="main_link">担当者確認</a></td>
            <td>{{ $row->code }}</td>
            <td class="large">{{ $row->name }}</td>
            <td>{{ $row->fullname }}</td>
            <td>{{ $row->phone }}</td>
            <td class="large">{{ $row->address }}</td>
            <td class="text-nowrap">{{ $row->hp }}</td>
            <td class="large text-overflow">{{ $row->note }}</td>
        </tr>
    @endforeach
@else
    <tr>
        <td colspan="10">
            <div class="text-center">データがありません。</div>
        </td>
    </tr>
@endif

resources/views/admin/clients/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- content-->
    <div class="d-flex align-items-center justify-content-between mb-30">
        <h2 class="title title-large"><i class="fas fa-building main_icon"></i>クライアント一覧</h2>
        <a href="{{ route('admin.client.create') }}" class="btn-custom btn-custom-warning md"><i
                class="fas fa-plus main_icon text-white"></i>クライアント新規登録</a>
    </div>
    <div class="card-custom mb-30">
        <form action="" class="form-custom">
            <div class="form-group mb-0">
                <div class="d-flex form-custom_search position-relative">
                    <input type="text" name="keyword" class="form-control input-search" value="{{ request()->keyword }}"
                           placeholder="検索したいワードを入力してください"/>
                    <i class="fas fa-search"></i>
                    <button type="submit" class="btn-custom btn-custom-primary">検索</button>
                </div>
            </div>
        </form>
    </div>

    <!-- alert -->
    @if ($message = Session::get('success'))
        <div class="alert alert-success" role="alert">
            <p class="mb-0">{{ $message }}</p>
        </div>
    @endif

    <!--table-->
    <div class="main_table">
        <div class="d-flex justify-content-between">
            <p class="fs-20">件数 {{ @$count }}件</p>
            <ul class="pagination">
                {!! $lists->appends($_GET)->links() !!}
            </ul>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered text-center mb-0">
                <thead>
                <tr>
                    <th scope="col" class="main_table_action">削除</th>
                    <th scope="col" class="main_table_action">編集</th>
                    <th scope="col">担当者</th>
                    <th scope="col">クライアントID<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt=""
                                                                    class="img-fluid mb-1 sort-heading"
                                                                    id="code" data-sort="asc"></span></th>
                    <th scope="col">組織名<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt=""
                                                               class="img-fluid mb-1 sort-heading" id="name" data-sort="asc"></span>
                    </th>
                    <th scope="col">代表者名<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt=""
                                                                class="img-fluid mb-1 sort-heading"
                                                                id="fullname" data-sort="asc"></span></th>
                    <th scope="col">電話番号<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt=""
                                                                class="img-fluid mb-1 sort-heading" id="tel" data-sort="asc"></span>
                    </th>
                    <th scope="col">住所<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt=""
                                                              class="img-fluid mb-1 sort-heading"
                                                              id="address" data-sort="asc"></span></th>
                    <th scope="col">HP<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt=""
                                                              class="img-fluid mb-1 sort-heading" id="hp" data-sort="asc"></span>
                    </th>
                    <th scope="col">備考<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt=""
                                                              class="img-fluid mb-1 sort-heading" id="note" data-sort="asc"></span>
                    </th>
                </tr>
                </thead>
                <tbody>
                @if($lists->isNotEmpty())
                    @foreach($lists as $row)
                        <tr>
                            <td class="main_table_action">
                                <a href="javascript:void(0);" data-id="{{ $row->id }}" data-url="{{ route('admin.client.destroy', $row->id) }}"
                                   class="delete-client {{ $row->check ? 'disable' : '' }}"
                                   data-toggle="modal" data-target="#deleteClient">
                                    <i class="fas fa-trash-alt main_icon m-0"></i>
                                </a>
                            </td>
                            <td class="main_table_action">
                                <a href="{{ route('admin.client.edit', $row->id) }}"><i
                                        class="fas fa-pen main_icon m-0"></i></a>
                            </td>
                            <td><a href="{{ route('admin.employee.index', $row->id) }}" class="main_link">担当者確認</a></td>
                            <td>{{ $row->code }}</td>
                            <td class="large text-overflow">{{ $row->name }}</td>
                            <td>{{ $row->fullname }}</td>
                            <td>{{ $row->phone }}</td>
                            <td class="large">{{ $row->address }}</td>
                            <td class="text-nowrap">{{ $row->hp }}</td>
                            <td class="large text-overflow">{{ $row->note }}</td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="10">
                            <div class="text-center">データがありません。</div>
                        </td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
        <div class="mt-2 d-flex justify-content-between mt-2">
            <p class="fs-20">件数 {{ @$count }}件</p>
            <ul class="pagination">
                {!! $lists->appends($_GET)->links() !!}
            </ul>
        </div>

        <input type="hidden" name="hidden_page" id="hidden_page" value="1"/>
        <input type="hidden" name="hidden_column_name" id="hidden_column_name" value="" />
        <input type="hidden" name="hidden_sort_type" id="hidden_sort_type" value="" />
    </div>

    <div class="modal fade modal-custom" id="deleteClient" role="dialog" aria-labelledby="deleteClient" aria-hidden="true">
        <div class="delete modal-dialog modal-confirm">
            <div class="modal-content">
                <form action="#" method="POST" id="form_delete_client">
                    @csrf
                    @method('DELETE')
                    <div class="modal-header mb-3">
                        <h3 class="title title-large mb-0"><i class="mr-2 fas fa-exclamation-triangle fs-20 color-red"></i>削除</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body p-0 mb-3 text-center fs-16">
                        <p>削除しますがよろしいですか</p>
                    </div>
                    <div class="modal-footer justify-content-center p-0 mb-1">
                        <button type="button" class="btn-custom btn-custom-disabled w-50" data-dismiss="modal">キャンセル</button>
                        <button type="submit" class="btn-custom btn-custom-danger w-50">削除</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        $(document).ready(function () {
            $(document).on('click', '.delete-client', function() {
                let url = $(this).data('url');
                $('#form_delete_client').attr('action', url);
            } );

            $(".sort-heading").on('click', function (e) {
                e.preventDefault();
                let sort_name = $(this).attr('id');
                let sort_by = $(this).data('sort');
                clearIcon(sort_name);

                let keyword = '{{ request()->keyword }}';
                let page = 1;
                $('#hidden_column_name').val(sort_name);
                $('#hidden_sort_type').val(sort_by);

                fetchData(page, sort_name, sort_by, keyword);
            });

            $(document).on('click', '.pagination a', function(e){
                e.preventDefault();
                let page = $(this).attr('href').split('page=')[1];
                $('#hidden_page').val(page);
                var column_name = $('#hidden_column_name').val();
                var sort_by = $('#hidden_sort_type').val();
                let keyword = '{{ request()->keyword }}';

                fetchData(page, column_name, sort_by, keyword);
            });

            function fetchData(page, column_name, sort_by, keyword) {
                let getId = column_name;
                let sortBy = sort_by;
                $.ajax({
                    url: '{{ route('admin.client.index') }}',
                    type: 'GET',
                    data: {
                        page: page,
                        column: column_name,
                        sortOrder: sort_by,
                        keyword: keyword,
                    },
                    beforeSend: showLoad(),
                    success:function(data) {
                        hideLoad();
                        if (sortBy == 'asc') {
                            $('#' + getId).data('sort', 'desc');
                            $('#' + getId).attr('src', '{{ asset('images/icons/sort-asc.svg') }}');
                        } else if (sortBy == 'desc') {
                            $('#' + getId).data('sort', 'all');
                            $('#' + getId).attr('src', '{{ asset('images/icons/sort-desc.svg') }}');
                        } else if (sortBy == 'all') {
                            $('#' + getId).data('sort', 'asc');
                            $('#' + getId).attr('src', '{{ asset('images/icons/sort.svg') }}');
                        }

                        $('ul.pagination').html(data.paginate);
                        $(".table tr:not(:first)").remove();
                        $(".table").append(data.data);
                        // window.history.pushState("", "", this.url);
                    }
                });
            }
        });
    </script>
@endpush