routes/admin.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::namespace('Admin')->group(function () {
    Route::get('/login', 'Auth\LoginController@login')->name('admin.login');
    Route::post('/check-login', 'Auth\LoginController@checkLogin')->name('admin.checkLogin');
    Route::get('/logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('/forgot-password', 'Auth\LoginController@forgot')->name('admin.forgot_pass');
    Route::post('/recover-pass', 'Auth\LoginController@recoverPass')->name('admin.recover_pass');
    Route::get('/activate', 'Auth\LoginController@updatePass')->name('admin.update_pass');
    Route::post('/reset-new-pass', 'Auth\LoginController@resetPass')->name('admin.reset_pass');
    Route::get('/contact', 'Auth\LoginController@contact')->name('admin.contact');

    Route::group(['middleware' => ['checkLogin:admin', 'checkAdmin'],  'as' => 'admin.'], function () {
        Route::get('/', 'AdminController@index')->name('index');
        Route::get('/create', 'AdminController@create')->name('create');
        Route::post('/store', 'AdminController@store')->name('store');
        Route::get('edit/{id}', 'AdminController@edit')->name('edit');
        Route::put('update/{id}', 'AdminController@update')->name('update');
        Route::delete('destroy/{id}', 'AdminController@destroy')->name('destroy');
        Route::group(['prefix' => 'client'], function () {
            Route::get('/', 'ClientController@index')->name('client.index');
            Route::get('create', 'ClientController@create')->name('client.create');
            Route::post('store', 'ClientController@store')->name('client.store');
            Route::get('edit/{id}', 'ClientController@edit')->name('client.edit');
            Route::put('update/{id}', 'ClientController@update')->name('client.update');
            Route::delete('destroy/{id}', 'ClientController@destroy')->name('client.destroy');

            Route::get('{client_id}/employee', 'EmployeeController@index')->name('employee.index');
            Route::get('{client_id}/employee/create', 'EmployeeController@create')->name('employee.create');
            Route::post('{client_id}/employee/store', 'EmployeeController@store')->name('employee.store');
            Route::get('{client_id}/employee/edit/{id}', 'EmployeeController@edit')->name('employee.edit');
            Route::put('{client_id}/employee/update/{id}', 'EmployeeController@update')->name('employee.update');
            Route::delete('{client_id}/employee/destroy/{id}', 'EmployeeController@destroy')->name('employee.destroy');
            Route::any('{slug}', function()
            {
                return view('errors.404');
            });
        });
        Route::any('{slug}', function()
        {
            return view('errors.404');
        });
    });
});

Route::fallback(function() {
    if (Auth::check() && Auth::user()->type == User::TYPE_ACCOUNT_AA){
        return redirect()->route('admin.index');
    }else {
        return redirect()->route('admin.login');
    }
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//Route::get('/', function () {
//    return view('template/home');
//})->name('home')->middleware('auth:client');
//
//Route::get('/', function () {
//    return view('template/home');
//});
//Route::get('/admin', function () {
//    return view('template/users/index');
//});

// Route::get('/admin/create-user', 'TemplateController@createUser');
//Route::get('/admin/manage', 'TemplateController@manage');
//Route::get('/admin/create-client', 'TemplateController@createClient');
// Route::get('/admin/create-ce', 'TemplateController@createCE');

//Route::get('/login', 'TemplateController@login');
//Route::get('/forgot-password', 'TemplateController@forgot');
//Route::get('/contact', 'TemplateController@contact');
//Route::get('/reset-password', 'TemplateController@resetPwd');

// Route::get('/create-question', 'TemplateController@createQuestion');
// Route::get('/question-list', 'TemplateController@questionList');
// Route::get('/preview', 'TemplateController@preview');
// Route::get('/address-list', 'TemplateController@addressList');
// Route::get('/create-address', 'TemplateController@createAddress');
// Route::get('/confirm-address', 'TemplateController@confirmAddress');
// Route::get('/create-csv', 'TemplateController@createCsv');
// Route::get('/csv-detail', 'TemplateController@csvDetail');
// Route::get('/statistic-list', 'TemplateController@statisticList');
// Route::get('/statistic-detail', 'TemplateController@statisticDetail');

resources/views/admin/admins/box_table.blade.php
@if($lists->isNotEmpty())
    @foreach($lists as $row)
        <tr>
            <td class="main_table_action">
                <a href="javascript:void(0);" data-id="{{ $row->id }}" data-url="{{ route('admin.destroy', $row->id) }}" class="delete-admin"
                   data-toggle="modal" data-target="#deleteAdmin">
                    <i class="fas fa-trash-alt main_icon m-0"></i>
                </a></td>
            <td class="main_table_action"><a href="{{ route('admin.edit', $row->id) }}"><i class="fas fa-pen main_icon m-0"></i></a></td>
            <td>{{ $row->code }}</td>
            <td class="title-survey text-overflow" data-toggle="tooltip" title="{{ $row->fullname }}">{{ $row->fullname }}</td>
            <td class="title-survey text-overflow" data-toggle="tooltip" title="{{ $row->furiname }}">{{ $row->furiname }}</td>
            <td class="text-nowrap">{{ $row->email }}</td>
            <td>{{ array_key_exists($row->role, $roles) ? $roles[$row->role] : '' }}</td>
        </tr>
    @endforeach
@else
    <tr>
        <td colspan="7">
            <div class="text-center">データがありません。</div>
        </td>
    </tr>
@endif

resources/views/admin/admins/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- content-->
    <div class="d-flex align-items-center justify-content-between mb-30">
        <h2 class="title title-large mb-0"><i class="fas fa-plus main_icon"></i>AAアカウント新規登録</h2>
    </div>
    <!--table-->
    <form action="{{ route('admin.store') }}" method="POST" id="frm" class="form-custom">
        @csrf
        <div class="card-custom card-table mb-30">
            <table class="table table-bordered mb-0">
                <tbody>
                <tr class="card-table_bg">
                    <th class="th-header">
                        アカウントID
                        @if($errors->has('code'))
                            <small class="form-text text-error">{{ $errors->first('code') }}</small>
                        @endif
                    </th>
                    <td>{{ $code }}<input type="hidden" name="code" value="{{ $code }}"></td>
                </tr>
                <tr>
                    <th class="th-header">パスワード <span class="card-table_label">必須</span>
                        @if($errors->has('password_admin'))
                            <small class="form-text text-error">{{ $errors->first('password_admin') }}</small>
                        @endif
                    </th>
                    <td>
                        <div class="row row-custom align-items-center">
                            <div class="col-7 col-custom">
                                <input type="text" name="password_admin" value="{{ str_replace('　', '', old('password_admin')) }}"
                                       class="form-control @if($errors->has('password_admin')) border-error @endif"
                                       placeholder="パスワードを入力してください" maxlength="255">
                            </div>
                            <span>※8文字以上、半角英数字</span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th class="th-header">氏名 <span class="card-table_label">必須</span>
                        @if($errors->has('first_name'))
                            <small class="form-text text-error">{{ $errors->first('first_name') }}</small>
                        @elseif($errors->has('last_name'))
                            <small class="form-text text-error">{{ $errors->first('last_name') }}</small>
                        @endif
                    </th>
                    <td>
                        <div class="row align-items-center">
                            <div class="col-2 col-custom">
                                <input type="text" name="last_name" value="{{ str_replace('　', '', old('last_name')) }}"
                                       class="form-control @if($errors->has('last_name')) border-error @endif"
                                       placeholder="田中" maxlength="255">
                            </div>
                            <div class="col-2 col-custom">
                                <input type="text" name="first_name" value="{{ str_replace('　', '', old('first_name')) }}"
                                       class="form-control @if($errors->has('first_name')) border-error @endif"
                                       placeholder="太郎" maxlength="255">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th class="th-header">フリガナ <span class="card-table_label">必須</span>
                        @if($errors->has('first_name_furi'))
                            <small class="form-text text-error">{{ $errors->first('first_name_furi') }}</small>
                        @elseif($errors->has('last_name_furi'))
                            <small class="form-text text-error">{{ $errors->first('last_name_furi') }}</small>
                        @endif
                    </th>
                    <td>
                        <div class="row align-items-center">
                            <div class="col-2 col-custom">
                                <input type="text" name="last_name_furi" value="{{ str_replace('　', '', old('last_name_furi')) }}"
                                       class="form-control @if($errors->has('last_name_furi')) border-error @endif"
                                       placeholder="タナカ" maxlength="255" >
                            </div>
                            <div class="col-2 col-custom">
                                <input type="text" name="first_name_furi" value="{{ str_replace('　', '', old('first_name_furi')) }}"
                                       class="form-control @if($errors->has('first_name_furi')) border-error @endif"
                                       placeholder="タロウ" maxlength="255">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th class="th-header">メールアドレス <span class="card-table_label">必須</span>
                        @if($errors->has('email'))
                            <small class="form-text text-error">{{ $errors->first('email') }}</small>
                        @endif
                    </th>
                    <td>
                        <div class="row align-items-center">
                            <div class="col-9 col-custom">
                                <input type="text" name="email" value="{{ str_replace('　', '', old('email')) }}"
                                       class="form-control @if($errors->has('email')) border-error @endif"
                                       placeholder="メールアドレスを入力してください" maxlength="255">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th class="th-header">権限 <span class="card-table_label">必須</span>
                        @if($errors->has('role'))
                            <small class="form-text text-error">{{ $errors->first('role') }}</small>
                        @endif
                    </th>
                    <td>
                        @foreach($roles as $key => $role)
                            <div class="form-check form-check-inline">
                                <input class="form-check-input @if($errors->has('role'))border-error @endif"
                                       type="radio" name="role" value="{{ $key }}" {{ (old('role') == $key) ? 'checked' : ''}}>
                                <label class="form-check-label pl-2">
                                    {{ $role }}
                                </label>
                            </div>
                        @endforeach
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="d-flex justify-content-center">
            <a href="{{ route('admin.index') }}" class="btn-custom btn-custom-disabled md mx-4 btn-custom-large">戻る</a>
            <button type="submit" id="btn-submit" class="btn-custom btn-custom-primary md mx-4 btn-custom-large">登録</button>
        </div>
    </form>
@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- content-->
    <div class="d-flex align-items-center justify-content-between mb-30">
        <h2 class="title title-large mb-0"><i class="fas fa-pen main_icon"></i>AAアカウント編集</h2>
    </div>
    <!--table-->
    <form action="{{ route('admin.update', $admin->id) }}" method="POST" id="frm" class="form-custom">
        @csrf
        {{ method_field('PUT') }}
        <div class="card-custom card-table mb-30">
            <table class="table table-bordered mb-0">
                <tbody>
                <tr class="card-table_bg">
                    <th>
                        アカウントID
                        @if($errors->has('code'))
                            <small class="form-text text-error">{{ $errors->first('code') }}</small>
                        @endif
                    </th>
                    <td>{{ $admin->code }}<input type="hidden" name="code" value="{{ $admin->code }}"></td>
                </tr>
                <tr>
                    <th class="th-header">パスワード <span class="card-table_label">必須</span>
                    </th>
                    <td>
                        <div class="row row-custom align-items-center">
                            <div class="col-7 col-custom">
                                <input type="password" value="********" class="form-control" disabled>
                            </div>
                            <span>※8文字以上、半角英数字</span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th class="th-header">氏名 <span class="card-table_label">必須</span>
                        @if($errors->has('first_name'))
                            <small class="form-text text-error">{{ $errors->first('first_name') }}</small>
                        @elseif($errors->has('last_name'))
                            <small class="form-text text-error">{{ $errors->first('last_name') }}</small>
                        @endif
                    </th>
                    <td>
                        <div class="row align-items-center">
                            <div class="col-2 col-custom">
                                <input type="text" name="last_name" value="{{ str_replace("　", '', old('last_name', $admin->last_name)) }}"
                                       class="form-control @if($errors->has('last_name')) border-error @endif"
                                       placeholder="田中" maxlength="255">
                            </div>
                            <div class="col-2 col-custom">
                                <input type="text" name="first_name" value="{{ str_replace("　", '', old('first_name', $admin->first_name)) }}"
                                       class="form-control @if($errors->has('first_name')) border-error @endif"
                                       placeholder="太郎" maxlength="255">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th class="th-header">フリガナ <span class="card-table_label">必須</span>
                        @if($errors->has('first_name_furi'))
                            <small class="form-text text-error">{{ $errors->first('first_name_furi') }}</small>
                        @elseif($errors->has('last_name_furi'))
                            <small class="form-text text-error">{{ $errors->first('last_name_furi') }}</small>
                        @endif
                    </th>
                    <td>
                        <div class="row align-items-center">
                            <div class="col-2 col-custom">
                                <input type="text" name="last_name_furi" value="{{ str_replace("　", '', old('last_name_furi', $admin->last_name_furi)) }}"
                                       class="form-control @if($errors->has('last_name_furi')) border-error @endif"
                                       placeholder="タナカ" maxlength="255">
                            </div>
                            <div class="col-2 col-custom">
                                <input type="text" name="first_name_furi" value="{{ str_replace("　", '', old('first_name_furi', $admin->first_name_furi)) }}"
                                       class="form-control @if($errors->has('first_name_furi')) border-error @endif"
                                       placeholder="タロウ" maxlength="255">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th class="th-header">メールアドレス <span class="card-table_label">必須</span>
                        @if($errors->has('email'))
                            <small class="form-text text-error">{{ $errors->first('email') }}</small>
                        @endif
                    </th>
                    <td>
                        <div class="row align-items-center">
                            <div class="col-9 col-custom">
                                <input type="text" name="email" value="{{ str_replace("　", '', old('email', $admin->email)) }}"
                                       class="form-control @if($errors->has('email')) border-error @endif"
                                       placeholder="メールアドレスを入力してください" maxlength="255">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th class="th-header">権限 <span class="card-table_label">必須</span>
                        @if($errors->has('role'))
                            <small class="form-text text-error">{{ $errors->first('role') }}</small>
                        @endif
                    </th>
                    <td>
                        @foreach($roles as $key => $role)
                            <div class="form-check form-check-inline">
                                <input class="form-check-input @if($errors->has('role'))border-error @endif"
                                       type="radio" name="role" value="{{ $key }}" {{ (old('role', $admin->role) == $key) ? 'checked' : ''}}>
                                <label class="form-check-label pl-2">
                                    {{ $role }}
                                </label>
                            </div>
                        @endforeach
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="d-flex justify-content-center">
            <a href="{{ route('admin.index') }}" class="btn-custom btn-custom-disabled md mx-4 btn-custom-large">戻る</a>
            <button type="submit" id="btn-submit" class="btn-custom btn-custom-primary md mx-4 btn-custom-large">編集</button>
        </div>
    </form>
@endsection

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <!-- content-->
    <div class="d-flex align-items-center justify-content-between mb-30">
        <h2 class="title title-large"><i class="fas fa-user main_icon"></i>AAアカウント一覧</h2>
        <a href="{{ route('admin.create') }}" class="btn-custom btn-custom-warning md"><i class="fas fa-plus main_icon text-white"></i>AAアカウント新規登録</a>
    </div>
    <div class="card-custom mb-30">
        <form action="" class="form-custom">
            <div class="form-group mb-0">
                <div class="d-flex form-custom_search position-relative">
                    <input type="text" name="keyword" class="form-control input-search" placeholder="検索したいワードを入力してください" value="{{ request()->keyword }}">
                    <i class="fas fa-search"></i>
                    <button type="submit" class="btn-custom btn-custom-primary">検索</button>
                </div>
            </div>
        </form>
    </div>

    <!-- alert -->
    @if ($message = Session::get('success'))
        <div class="alert alert-success" role="alert">
            <p class="mb-0">{{ $message }}</p>
        </div>
    @endif
    @if ($message = Session::get('error'))
        <div class="alert alert-danger" role="alert">
            <p class="mb-0">{{ $message }}</p>
        </div>
    @endif
    <!--table-->
    <div class="main_table">
        <div class="d-flex justify-content-between">
            <p class="fs-20">件数 {{ @$count }}件</p>
            <ul class="pagination">
                {!! $lists->appends($_GET)->links() !!}
            </ul>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered text-center mb-0">
                <thead>
                <tr>
                    <th scope="col" class="main_table_action">削除</th>
                    <th scope="col" class="main_table_action">編集</th>
                    <th scope="col">アカウントID<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt="" class="img-fluid mb-1 sort-heading" id="code" data-sort="asc"></span></th>
                    <th scope="col">氏名<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt="" class="img-fluid mb-1 sort-heading" id="fullname" data-sort="asc"></span></th>
                    <th scope="col">フリガナ<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt="" class="img-fluid mb-1 sort-heading" id="furiname" data-sort="asc"></span></th>
                    <th scope="col">メールアドレス<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt="" class="img-fluid mb-1 sort-heading" id="email" data-sort="asc"></span></th>
                    <th scope="col">権限<span class="ml-1"><img src="{{ asset('images/icons/sort.svg') }}" alt="" class="img-fluid mb-1 sort-heading" id="role" data-sort="asc"></span></th>
                </tr>
                </thead>
                <tbody>
                @if($lists->isNotEmpty())
                    @foreach($lists as $row)
                        <tr>
                            <td class="main_table_action">
                                <a href="javascript:void(0);" data-id="{{ $row->id }}" data-url="{{ route('admin.destroy', $row->id) }}" class="delete-admin"
                                   data-toggle="modal" data-target="#deleteAdmin">
                                    <i class="fas fa-trash-alt main_icon m-0"></i>
                                </a>
                            </td>
                            <td class="main_table_action"><a href="{{ route('admin.edit', $row->id) }}"><i class="fas fa-pen main_icon m-0"></i></a></td>
                            <td>{{ $row->code }}</td>
                            <td class="title-survey text-overflow" data-toggle="tooltip" title="{{ $row->fullname }}">{{ $row->fullname }}</td>
                            <td class="title-survey text-overflow" data-toggle="tooltip" title="{{ $row->furiname }}">{{ $row->furiname }}</td>
                            <td class="text-nowrap">{{ $row->email }}</td>
                            <td>{{ array_key_exists($row->role, $roles) ? $roles[$row->role] : '' }}</td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td colspan="7">
                            <div class="text-center">データがありません。</div>
                        </td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
        <div class="mt-2 d-flex justify-content-between">
            <p class="fs-20">件数 {{ @$count }}件</p>
            <ul class="pagination">
                {!! $lists->appends($_GET)->links() !!}
            </ul>
        </div>

        <input type="hidden" name="hidden_page" id="hidden_page" value="1"/>
        <input type="hidden" name="hidden_column_name" id="hidden_column_name" value="" />
        <input type="hidden" name="hidden_sort_type" id="hidden_sort_type" value="" />
    </div>

    <div class="modal fade modal-custom" id="deleteAdmin" role="dialog" aria-labelledby="deleteAdmin" aria-hidden="true">
        <div class="delete modal-dialog modal-confirm">
            <div class="modal-content">
                <form action="#" method="POST" id="form_delete_admin">
                    @csrf
                    @method('DELETE')
                    <div class="modal-header mb-3">
                        <h3 class="title title-large mb-0"><i class="mr-2 fas fa-exclamation-triangle fs-20 color-red"></i>削除</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body p-0 mb-3 text-center fs-16">
                        <p>削除しますがよろしいですか</p>
                    </div>
                    <div class="modal-footer justify-content-center p-0 mb-1">
                        <button type="button" class="btn-custom btn-custom-disabled w-50" data-dismiss="modal">キャンセル</button>
                        <button type="submit" class="btn-custom btn-custom-danger w-50">削除</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('script')
    <script>
        $(document).ready(function () {
            $(document).on('click', '.delete-admin', function() {
                let url = $(this).data('url');
                $('#form_delete_admin').attr('action', url);
            } );

            $(".sort-heading").on('click', function (e) {
                e.preventDefault();
                let sort_name = $(this).attr('id');
                let sort_by = $(this).data('sort');
                clearIcon(sort_name);

                let keyword = '{{ request()->keyword }}';
                let page = 1;
                $('#hidden_column_name').val(sort_name);
                $('#hidden_sort_type').val(sort_by);

                fetchData(page, sort_name, sort_by, keyword);
            });

            $(document).on('click', '.pagination a', function(e){
                e.preventDefault();
                let page = $(this).attr('href').split('page=')[1];
                $('#hidden_page').val(page);
                var column_name = $('#hidden_column_name').val();
                var sort_by = $('#hidden_sort_type').val();
                let keyword = '{{ request()->keyword }}';

                fetchData(page, column_name, sort_by, keyword);
            });

            function fetchData(page, column_name, sort_by, keyword) {
                let getId = column_name;
                let sortBy = sort_by;
                $.ajax({
                    url: '{{ route('admin.index') }}',
                    type: 'GET',
                    data: {
                        page: page,
                        column: column_name,
                        sortOrder: sort_by,
                        keyword: keyword,
                    },
                    beforeSend: showLoad(),
                    success:function(data) {
                        hideLoad();
                        if (sortBy == 'asc') {
                            $('#' + getId).data('sort', 'desc');
                            $('#' + getId).attr('src', '{{ asset('images/icons/sort-asc.svg') }}');
                        } else if (sortBy == 'desc') {
                            $('#' + getId).data('sort', 'all');
                            $('#' + getId).attr('src', '{{ asset('images/icons/sort-desc.svg') }}');
                        } else if (sortBy == 'all') {
                            $('#' + getId).data('sort', 'asc');
                            $('#' + getId).attr('src', '{{ asset('images/icons/sort.svg') }}');
                        }

                        $('ul.pagination').html(data.paginate);
                        $(".table tr:not(:first)").remove();
                        $(".table").append(data.data);
                        // window.history.pushState("", "", this.url);
                    }
                });
            }
        });
    </script>
@endpush